CREATE TABLE alumno (
  NoControl INT(8) PRIMARY KEY NOT NULL,
  username VARCHAR(100) NOT NULL,
  fullname VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  Semestre INT(12) NOT NULL,
  Carrera VARCHAR(50) NOT NULL,
  password VARCHAR(60) NOT NULL
);
