CREATE TABLE alumno (
  id INT(11) NOT NULL,
  NoControl VARCHAR(8) NOT NULL,
  username VARCHAR(100) NOT NULL,
  fullname VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  Semestre INT(12) NOT NULL,
  Carrera VARCHAR(50) NOT NULL,
  password VARCHAR(60) NOT NULL
);

ALTER TABLE alumno
  ADD PRIMARY KEY (id);
ALTER TABLE alumno
  MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 2;
